# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mike Giarlo
author: Mike Giarlo
email: leftwing@alumni.rutgers.edu
description: Digital Library Whatchamacallit
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mike.giarlo.name" # the base hostname & protocol for your site
twitter_username: mjgiarlo
github_username:  mjgiarlo

# Permalink settings
permalink: /blog/:year/:month/:day/:title/

# Build settings
markdown: kramdown

# Plugins
gems:
  - octopress-image-tag
  - octopress-codeblock
  - octopress-quote-tag
  - octopress-codefence
  - octopress-gist
